#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
#
# gen-repo-map.sh — generate docs/architecture/REPOSITORY-MAP.adoc from the
# tree plus the annotations in .machine_readable/root-allow.txt.
#
# WHY THIS IS GENERATED. Before this existed the repo carried FIVE hand-written
# maps and not one was accurate: README's table omitted 12 directories,
# .github/DIRECTORY.adoc was a 3-line stub, .github/CONTRIBUTING.md drew a tree
# naming lib/, extensions/, plugins/ and spec/ (none of which exist),
# docs/README.adoc was wrong on every path it named, and docs/RSR_OUTLINE.adoc
# was a second whole-repo README contradicting the first. They rotted because
# nothing checked them. A map that is regenerated and diffed in CI cannot.
#
# Usage: bash scripts/gen-repo-map.sh [repo_root]
set -euo pipefail

# Byte order, everywhere. `sort` is LOCALE-DEPENDENT: under en_US.UTF-8 it
# ignores leading punctuation, so dotfiles interleave with ordinary names;
# under LC_ALL=C (what CI runs) they sort first. The generator was therefore
# deterministic WITHIN an environment but not ACROSS environments, and the
# CI freshness check caught precisely that on its first real run. Running the
# generator twice in one shell cannot detect it - the check must vary the
# locale, which is what tests/shape/repo_map_determinism_test.sh now does.
export LC_ALL=C

REPO_ROOT="${1:-.}"
cd "$REPO_ROOT"
ALLOW=".machine_readable/root-allow.txt"
OUT="docs/architecture/REPOSITORY-MAP.adoc"

[ -f "$ALLOW" ] || { echo "ERROR: $ALLOW not found" >&2; exit 2; }
mkdir -p "$(dirname "$OUT")"

# Root entries, tracked shape only (mirrors check-root-shape.sh).
mapfile -t ENTRIES < <(git ls-files | awk -F/ '{print $1}' | sort -u)

# name -> annotation, harvested from the allowlist's own comments.
declare -A NOTE=() OPTIONAL=()
while IFS= read -r line; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line// }" ]] && continue
    raw="${line%%#*}"; raw="$(echo "$raw" | xargs || true)"
    [ -z "$raw" ] && continue
    comment="${line#*#}"; [ "$comment" = "$line" ] && comment=""
    comment="$(echo "$comment" | xargs || true)"
    key="${raw%/}"
    if [[ "$key" == '?'* ]]; then key="${key#\?}"; OPTIONAL["$key"]=1; fi
    NOTE["$key"]="$comment"
done < "$ALLOW"

# Directories whose own level holds nothing but a stub README (or .gitkeep).
# The owner ruling (2026-08-26) is that these stay: they are DECLARED STRUCTURE,
# a statement of intended shape for repos minted from this template, not
# abandoned work. Saying so explicitly is the difference between the two.
# Recursive: a directory counts as unfilled only when its WHOLE subtree holds
# no substantive file. Checking just its own level would flag archetypes/, whose
# julia-library/ child is real content. (The ply manifests that once padded
# these counts were folded into the repo deed — standards#837 pilot.)
declared_only() {
    local d="$1" n
    n=$(git ls-files "$d" | awk -F/ '{print $NF}' \
        | grep -vxE 'README\.adoc|\.gitkeep' | wc -l)
    [ "$n" -eq 0 ]
}

{
  echo "// SPDX-License-Identifier: CC-BY-SA-4.0"
  echo "// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>"
  echo "//"
  echo "// GENERATED by scripts/gen-repo-map.sh - do not hand-edit."
  echo "// Regenerate with \`just repo-map\`. CI fails if this file is stale."
  echo "= Repository map"
  echo ":toc:"
  echo
  echo "The single authoritative map of this repository. It is generated from the"
  echo "tree and from the annotations in \`.machine_readable/root-allow.txt\`, and CI"
  echo "fails if it drifts, so it cannot rot the way its five hand-written"
  echo "predecessors did."
  echo
  echo "== Root"
  echo
  echo '[cols="2,1,4",options="header"]'
  echo '|==='
  echo "| Path | Required | What it is, and who reads it"
  echo
  for e in "${ENTRIES[@]}"; do
      [ -d "$e" ] && disp="\`$e/\`" || disp="\`$e\`"
      req="yes"; [ -n "${OPTIONAL[$e]+x}" ] && req="optional"
      note="${NOTE[$e]:-}"
      [ -z "$note" ] && note="-"
      echo "| $disp"
      echo "| $req"
      echo "| $note"
      echo
  done
  echo '|==='
  echo
  echo "== Declared structure not yet filled"
  echo
  echo "These directories currently hold only a stub \`README.adoc\` and a level"
  echo "manifest. That is deliberate. They declare the shape a repository minted"
  echo "from this template is expected to grow into; they are *intended"
  echo "structure, not abandoned work*. Add content, or delete the directory in"
  echo "your own repo - but do not read their emptiness as neglect here."
  echo
  first=1
  for d in $(git ls-files | grep '/' | sed 's|/[^/]*$||' | sort -u); do
      if declared_only "$d"; then
          [ $first -eq 1 ] && { echo "[cols=\"1\"]"; echo '|==='; first=0; }
          echo "| \`$d/\`"
      fi
  done
  [ $first -eq 0 ] && echo '|==='
  echo
  echo "== Where things are enforced"
  echo
  echo "* Root shape - \`scripts/check-root-shape.sh\` against"
  echo "  \`.machine_readable/root-allow.txt\`, run by \`.github/workflows/estate-rules.yml\`."
  echo "  The check is bidirectional: unlisted entries fail, and required entries"
  echo "  that are absent also fail."
  echo "* This map - \`just repo-map\` must produce no diff."
  echo "* Community health - GitHub reads \`.github/\` and no other path."
  echo "* Variant divergence - \`scripts/check-variant-drift.sh\` compares a child"
  echo "  to its parent BY PATH, so any move here invalidates every child's"
  echo "  declared path lists until they are re-anchored."
} > "$OUT"

echo "repo-map: wrote $OUT"
